### ISSUE TITLE
Subscript in node label

### ISSUE THREAD

**Issue by trya2l** [Jollywatt/typst-fletcher#17]
Hi,

Sorry if this is not related to fletcher (it may be due to me being new to typst).

I am currently trying to stylize the `label` of a `node` but I can't find the correct syntax.

Here is what I have tried:

`node((0,0), label: [F#sub[1]], radius: 1em)`
`node((0,0), F#sub[1], radius: 1em)`

Is it possible ? If so, how can I do it ?

Thanks (for the work, and the answer) :)

**Comment by trya2l** [comment]
Haha, it was just a small tweak. This worked: `node((0,0), [F#sub[1]], radius: 1em)`

**Comment by Jollywatt** [comment]
By the way, you can also use math mode with $...$ if you're wanting an equation:

```typc
node((0,0), $F_1$, radius: 1em)
```
