### ISSUE TITLE
Double node outline

### ISSUE THREAD

**Issue by Goldmensch** [Jollywatt/typst-fletcher#2]
Hi, I want to express a finite state machine via a graph. But for special nodes I have to use a double outline, but currently this seems not to be supported by this library. Is there any chance this could be added?

EDIT: A current workaround is to just add another node at the same position, with the same label. But then the font is a bild more bold than the others. A empty label doesn't work either with the error "cannot divide by zero".

![image](https://github.com/Jollywatt/typst-fletcher/assets/47005420/9a5eeada-4217-488f-830c-e330ada780cd)

```typst
#let graph = fletcher.diagram(
  node-outset: 4pt,
  spacing: (15mm, 8mm),
  node-stroke: black + 0.5pt,
  node((0, 0), $s_1$, ),
  node((1, 0), $s_2$ ),
  node((1, 0), $s_2$, inset: 9pt),
  edge((0, 0), (1, 0), "->", label: $a$, bend: 20deg),
  edge((0, 0), (0, 0), "->", label: $b$, bend: 120deg),
  edge((1, 0), (0, 0), "->", label: $b$, bend: 20deg),
  edge((1, 0), (1, 0), "->", label: $a$, bend: 120deg),
)
```

**Comment by Jollywatt** [comment]
Good idea. I just added this feature via an option called `extrude` for `node()`, which works like the `extrude` option for `edge()`.

So you could do:
```typ
#fletcher.diagram(
  node-outset: 4pt,
  spacing: (15mm, 8mm),
  node-stroke: black + 0.5pt,
  node((0, 0), $s_1$),
  node((1, 0), $s_2$, extrude: (0, 3)), // make an outer stroke at 3× the stroke's thickness
  edge((0, 0), (1, 0), "->", label: $a$, bend: 20deg),
  edge((0, 0), (0, 0), "->", label: $b$, bend: 120deg),
  edge((1, 0), (0, 0), "->", label: $b$, bend: 20deg),
  edge((1, 0), (1, 0), "->", label: $a$, bend: 120deg),
)
```

Not sure how long it takes for package updates to come through. But if you’re working locally, you can clone https://github.com/Jollywatt/typst-fletcher and use `#import "@local/fletcher:0.3.0"`.
The [manual](https://github.com/Jollywatt/typst-fletcher/raw/master/docs/manual.pdf) is updated, too.
