### ISSUE TITLE
Version 0.4.4 not found from registry

### ISSUE THREAD

**Issue by Nicceboy** [Jollywatt/typst-fletcher#23]
Hello,

when trying to use the example import
```typst
#import "@preview/fletcher:0.4.4" as fletcher: diagram, node, edge
```

It does not find the version 0.4.4

0.4.3 or 0.4.2 works. Is this removed by accident? I also don't find repository tags for 0.4.3 or 0.4.4

**Comment by Jollywatt** [comment]
Oh yeah, that's because v0.4.4 isn't published yet. I probably should keep any examples that only work on the dev version hidden away on a dev branch until the version is actually published!

**Comment by Nicceboy** [comment]
Ah, I see. I guess we can close this then.
