### ISSUE TITLE
Add support for edge labels to follow edges

### ISSUE THREAD

**Issue by TakodaS** [Jollywatt/typst-fletcher#27]
Unless I am mistaken, it is currently not possible to have edge labels follow the edge they are attached to. Unfortunately, using the builtin `rotate` function causes `diagram`  to become very confused leading to spacing issues.

```typst
#import "@preview/fletcher:0.4.3" as fletcher: diagram, node, edge

#diagram(
  debug: 3, node((0, 0), "A"), node((0, 1), "B"), edge(
    (-1, 0), (-1, 1), "->", rotate(-90deg)[Some complicated flow], label-side: right,
  ), node((0, 3), "C"), node((1, 4), "D"), edge(
    (0, 3), (1, 4), "->", rotate(45deg)[Some complicated flow], label-side: right,
  ),
)
```
![fletcher-issue(1)](https://github.com/Jollywatt/typst-fletcher/assets/49280242/fed5cbc1-d72e-4e7d-8513-8006dcd0cadf)

**Comment by Jollywatt** [comment]
Try using `rotate(reflow: true)`?

**Comment by TakodaS** [comment]
Ah it was right there in the typst documentation! Much appreciated! It is getting there but still doesn't work properly for the 45deg label

```typst
#import "@preview/fletcher:0.4.3" as fletcher: diagram, node, edge
#set page(width: 270pt, height: 320pt)

#diagram(
  debug: 3, node((0, 0), "A"), node((0, 1), "B"), edge(
    (-1, 0), (-1, 1), "->", rotate(-90deg, reflow: true)[Some complicated flow], label-side: right,
  ), node((0, 3), "C"), node((2, 5), "D"), edge(
    (0, 3), (2, 5), "->", rotate(45deg, reflow: true)[Some complicated flow], label-side: left,
  ),
)
```

![fletcher-issue(3)](https://github.com/Jollywatt/typst-fletcher/assets/49280242/d179c82a-463c-4f96-98f5-88df55ea7348)

I think this behavior should be by default in fletcher, maybe eventually leading to "text along path" functionality like in latex. What do you think?

**Comment by Jollywatt** [comment]
Yeah, that looks wrong - and worse I can't seem to fix it by playing around. Since this is so hard, automatic rotation of labels along (straight) edges would be a good feature to add.

**Comment by Jollywatt** [comment]
This has been added in 7ba5655!
