### ISSUE TITLE
Enclose does not work in Typst Online IDE

### ISSUE THREAD

**Issue by moritzketzer** [Jollywatt/typst-fletcher#28]
Hi,

I am not able to get `enclose` to work:

![CleanShot 2024-05-03 at 11 03 28@2x](https://github.com/Jollywatt/typst-fletcher/assets/48527611/ab4b3df0-9e8a-4caf-80b3-98f7378e765e)

What might be the problem?

**Comment by Jollywatt** [comment]
`enclose` was added in v0.4.4, which has [just been merged](https://github.com/typst/packages/pull/611) and so is available :)

**Comment by moritzketzer** [comment]
Thanks! :)
