### ISSUE TITLE
More fine-grained control of enclose

### ISSUE THREAD

**Issue by moritzketzer** [Jollywatt/typst-fletcher#30]
I would like to have more fine-grained control to enclose nodes, i.e., right now enclose snaps directly around the nodes, but I would like to have more control of the spacing.

Is there another way to use rectangles with rounded edges around nodes that I can place at will?

**Comment by Jollywatt** [comment]
If setting the `inset` and `corner-radius` options of the enclosing node doesn't give you enough control, the backup solution is to use the `diagram(render: ..)` option to draw things with CeTZ directly. CeTZ interop is still a little awkward, but there's an example in the manual.

**Comment by moritzketzer** [comment]
Thanks!
