### ISSUE TITLE
How to set edge label font size globally?

### ISSUE THREAD

**Issue by hooyuser** [Jollywatt/typst-fletcher#35]
Hi, I'm currently trying to adjust the edge label font size globally across all diagrams. In LaTeX, using the tikzcd package, the edge label text is smaller by default, as the following image shows:

![ima](https://i.upmath.me/svg/%5Cbegin%7Btikzcd%7D%0Af%20%5Carrow%5Br%2C%20%22f%22%5D%20%5Carrow%5Bd%5D%20%26%20f%20%5C%5C%0Af%20%5Carrow%5Bru%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%26%20%20%0A%5Cend%7Btikzcd%7D)

I'm looking for a way to achieve a similar appearance with typst-fletcher. Could you provide guidance on how to globally set the edge label font size? 

Additionally, I would like to know if there are any plans to make smaller edge labels the default appearance in future versions, considering its common use in math books. Thank you for your help!

**Comment by Jollywatt** [comment]
This is currently a gap in fletcher. I think it's worth adding a `label-size` option to `diagram()` (and `edge()` for completeness) which inserts a `set` rule before the label, since this is probably common.

At the moment, the thing one might do is to define a wrapper that applies the desired style:
```typ
#let ls(it) = text(0.8em, it) // [l]abel [s]ize

#diagram(
  $
  f edge("d", ->) edge(->, ls(f)) & f \
  f edge("ur", ->)
  $,
)

#diagram(
  node((0,0), [A]),
  edge(ls[hello]),
  node((1,1), [B])
)
```
Of course, this isn't as elegant as it could be, since it requires you to define a function and call it on every label yourself.

**Comment by Jollywatt** [comment]
Added in

**Comment by hooyuser** [comment]
@Jollywatt Thanks for your awesome work on the recent commit [6e7b5f3](https://github.com/Jollywatt/typst-fletcher/commit/6e7b5f30d98e51a21ba367f8e4c68328bd8a78ab). It's a lifesaver!

Could we consider bumping the version number for the Typst official package? This would allow users to start taking advantage of the new features right away.

**Comment by Jollywatt** [comment]
Yeah, one thing I don't have the hang of is best practices for versioning and release cycles:P

This feature has been bundled with a whole lot of other changes for version v0.5.0, which is slightly breaking. That will happen this week. Hopefully it won't be too painful to update!
