### ISSUE TITLE
An unexpected line break in the diagram

### ISSUE THREAD

**Issue by crimestop** [Jollywatt/typst-fletcher#39]
The package seems not compatible with `#set par(justify: true)`. The following code will generate an unexpected line break in the diagram
```
#import "@preview/fletcher:0.4.5" as fletcher: diagram, node, edge
#set par(justify: true)
#diagram( $
U union v  \
$)
```
<img width="929" alt="image" src="https://github.com/Jollywatt/typst-fletcher/assets/29431901/0d6c83ce-e13c-4743-94ed-8b5d5e45aad9">

**Comment by Jollywatt** [comment]
I don't see this bug in later typst/fletcher versions. Please reopen if you see it again
