### ISSUE TITLE
commuting square arrow mark

### ISSUE THREAD

**Issue by AHaliq** [Jollywatt/typst-fletcher#50]
I was wondering if theres an easy way to notate commuting squares in fletcher? quiver.io for latex uses an arrow with an invisible line with a mark at origin that looks like a square corner.

see at the corner of $A$ below

<img width="349" alt="Screenshot 2024-09-09 at 4 28 06 PM" src="https://github.com/user-attachments/assets/f0306a70-0677-445a-935f-4675e25ead86">

**Comment by Jollywatt** [comment]
(I thought this was the standard notation for a pullback? A commutative diagram has no special notation to show that it is commutative.)

Anyway, there isn't a ready-made way in fletcher, but you could implement the invisible-arrow idea like this:

```typ
#let corner-mark = (
  inherit: "straight",
  sharpness: 45deg,
  stroke: black,
  rev: false,
  
)

#let corner(..a) = edge(..a, stroke: white, marks: (corner-mark,))

#fletcher.diagram($
  A edge(->) edge("d", ->) corner("dr") & B edge("d", ->) \
  C edge(->) & D
$)
```

<img width="245" alt="Screenshot 2024-09-09 at 16 55 01" src="https://github.com/user-attachments/assets/6b4bf315-ef0b-4fa3-b55f-1f87713082f0">

**Comment by AHaliq** [comment]
ur right, i meant pullback. 😅

this solved my issue, thanks.

**Comment by Trebor-Huang** [comment]
There is the caveat that when the square is not perfectly square, the mark will be slightly rotated. Is there an easy solution to make the rotation snap to the closest, say 45deg angle?

**Comment by Jollywatt** [comment]
> There is the caveat that when the square is not perfectly square, the mark will be slightly rotated. Is there an easy solution to make the rotation snap to the closest, say 45deg angle?

Good point. You could do this instead:

```typ
#import "@preview/fletcher:0.5.7" : diagram, node, edge

#let corner-mark = (
  inherit: "straight",
  sharpness: 45deg,
  stroke: black,
  rev: false,
)

#let corner(a) = edge((rel: (a, 1.5em)), stroke: white, marks: (corner-mark,))

#diagram($
  A edge(->) edge("d", ->) #corner(-45deg) & B edge("d", ->) \
  C edge(->) & D stretch(=, size: #1cm) D
$)
```

This way, the corner "edge" sticks out 1.5em at the given angle, instead of toward another node.

**Comment by tomdjong** [comment]
Just to record this here in case others (like me) find this issue as part of their search. I had more success with the following:
```typst
#let pullback(..args) = edge(..args, " ", "dr", label: sym.corner.r.b, label-side: center, label-pos: 0.1)

// e.g.
#diagram($
  A edge(->) edge("d", ->) #pullback() & B edge("d", ->) \
  C edge(->) & D stretch(=, size: #1cm) D
$)
```

**Comment by BinaryQuantumSoul** [comment]
> Just to record this here in case others (like me) find this issue as part of their search. I had more success with the following:
> 
> #let pullback(..args) = edge(..args, " ", "dr", label: sym.corner.r.b, label-side: center, label-pos: 0.1)
> 
> // e.g.
> #diagram($
>   A edge(->) edge("d", ->) #pullback() & B edge("d", ->) \
>   C edge(->) & D stretch(=, size: #1cm) D
> $)

I had the same idea ! `sym.angle.right` works too.
Note that you can do adjunctions using a similar trick: https://github.com/Jollywatt/typst-fletcher/issues/96#issuecomment-4651303276.

**Comment by kontheocharis** [comment]
I found that using the "right angle" unicode character and rotating it looks better in my setup

```typst
#let pullback(..args) = edge(
  ..args,
  " ",
  "dr",
  label: rotate(-90deg, "∟"),
  label-side: center,
  label-pos: 0,
)

```

**Comment by BinaryQuantumSoul** [comment]
> I found that using the "right angle" unicode character and rotating it looks better in my setup

Isn't it the same that what I did?
