### ISSUE TITLE
Add support for anchors

### ISSUE THREAD

**Issue by iverks** [Jollywatt/typst-fletcher#59]
# Problem

When adding a slightly too high bend to an edge going to a very wide node, I get some weird effects. 

![image](https://github.com/user-attachments/assets/8a1f008c-70b1-421d-9487-a1324aa8b77a)

```typ
#figure(
  diagram(
    node-fill: color.transparentize(red, 60%),
    node-stroke: color.transparentize(red, 20%),
    // cell-size: 0mm,
    node((0, 0), [Initial structure model], name: <sm>),
    edge("-|>"),
    node((0, 1), [Calculate intensities $Fc^2$], name: <ci>),
    edge("-|>"),
    node((0, 2), [Calculate difference\ between $Fo^2$ and $Fc^2$], name: <cd>),
    edge("-|>"),
    node((0, 3), [Convergence], name: <conv>),
    edge(text(eastern,[yes]), "-|>"),
    node((0, 4), [Final model], name: <fin>),

    edge((0, 3), (1, 2), text(red, [no]), "-|>", bend: -25deg),
    node((1, 2), [Calculate corrections\ (add/remove atoms)], name: <cc>),
    edge(<cc>, <ci>, "-|>", bend: -30deg), // THIS IS THE ONE
  ),
  caption: [Flow chart of refinement],
) <refinement_flowchart>
```

# Proposed solution

By adding support for [CeTZ style anchors](https://cetz-package.github.io/docs/basics/anchors), I would be able to specify that the arrow should start at the first node's north position and end at the second node's east position

```typ
...
   edge((name: <cc>, anchor: 90deg), (name: <ci>, anchor: 0deg), "-|>", bend: -30deg), // THIS IS THE ONE
...
```

**Comment by Jollywatt** [comment]
Basic cetz anchors are implemented in ca3ecde057551ef396acd24c76c1cec7511ef714!

You can now do:
```typ
...
edge(<conv.east>, <cc.south>, text(red, [no]), "-|>", bend: -20deg),
edge(<cc.north>, <ci.east>, "-|>", bend: -30deg),
...
```
<img width="628" alt="Screenshot 2024-11-24 at 17 13 55" src="https://github.com/user-attachments/assets/14ab4b82-434b-4c68-815b-9b407cf7e3f0">

You can also use angle anchors like `(name: "cc", anchor: 45deg)`, etc.
