### ISSUE TITLE
Question: Can you get x or y of a label and use them as coordinates in edge?

### ISSUE THREAD

**Issue by chardskarth** [Jollywatt/typst-fletcher#69]
Example:
```
   ...
    node((0,0), <apiFileStorage>, ...)
    node((1,1), <apiSftpFileStorage>, ...)
    edge((<apiSftpFileStorage>.x, 1), (0, <apiFileStorage>.y), "-|>", ..edgeText[serves files], label-pos: .6),
   ...
```

**Comment by Jollywatt** [comment]
You can use cetz coordinate expressions for this. For example, the coordinate expression `((x1, y1), "|-", (x2, y2))` resolves to `(x1, y2)`. So you could try something like `(<apiSftpFileStorage>, "|-", (1, 1))` or `(<apiFileStorage>, "-|", (0,0))` depending on the context.

**Comment by chardskarth** [comment]
I'm new to this, so Im not sure I follow. 

This `(1,1)` will be in relative position to `apiSftpFileStorage`?

**Comment by chardskarth** [comment]
I think I got it. 

What I wanted could be achieved by cetz' [relative coordinate expressions](https://github.com/Jollywatt/typst-fletcher/blob/3cc9a1829116c9303dc7aa3e96084e0b7b8c0c83/docs/manual.typ#L471)

```
   ...
    node((0,0), <apiFileStorage>, ...)
    node((1,1), <apiSftpFileStorage>, ...)
    edge((rel: (0, 1), to: <apiSftpFileStorage>), (rel: (0, 0), to: <apiFileStorage>), "-|>", ..edgeText[serves files], label-pos: .6),
   ...
```

But I was able to achieve by what you mentioned, perpendicular coordinate expression. Thanks!
